import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Lazy } from 'react-lazy-io';

import imageData from '../data/images.json';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Lazy.Container
          options={{
            rootMargin: '0px 0px 100px 0px',
          }}
        >
          {imageData.map((data) => (
            <Lazy.Image
              src={data.url}
              width={data.width}
              height={data.height}
              alt={data.id}
              transitionDuration={1.5}
            >
              <Lazy.Placeholder
                className="placeholder"
                style={{ width: `${data.width}px`, height: `${data.height}px` }}
              />
            </Lazy.Image>
          ))}
        </Lazy.Container>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
